server:
  port: 8080

spring:
  profiles:
    active: local  # ??? profile ??
    # 'local' 또는 'prod' 프로파일이 활성화되면 해당 파일을 읽어옴
    # optional: 은 파일이 없어도 오류를 발생시키지 않음
    import:
      - optional:classpath:application-local.yml
      - optional:classpath:application-prod.yml


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    root: INFO
