server:
  port: 8080

spring:
  profiles:
    active: local  # ??? profile ??
    # 'local' 또는 'prod' 프로파일이 활성화되면 해당 파일을 읽어옴
    # optional: 은 파일이 없어도 오류를 발생시키지 않음
    import:
      - optional:classpath:application-local.yml
      - optional:classpath:application-prod.yml


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    root: INFO
    com.minseok.coursepalette: DEBUG # 개발 중 패키지 로그 레벨 상세 설정
    software.amazon.awssdk: INFO # AWS SDK 로그 (필요시 DEBUG로 변경하여 상세 확인)
    org.apache.ibatis: DEBUG # MyBatis 로그 (필요시 TRACE로 변경하여 SQL 확인)
    org.springframework.web: INFO # Spring Web 로그

aws:
  region: ap-northeast-2
  s3:
    bucket-name: ${S3_BUCKET_NAME} # S3 버킷 이름 (!!환경 변수 S3_BUCKET_NAME 필수 설정!!)
